# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
    
    # # Window transparency settings
    # active_opacity = 0.8
    # inactive_opacity = 0.7
    # fullscreen_opacity = 0.9
    
    # # Enable blur for better transparency effect
    # blur {
    #     enabled = true
    #     size = 1
    #     passes = 3
    #     new_optimizations = true
    # }
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
